import type { Site } from "@/types";

export const siteConfig: Site = {
  name: "devanshyadav.in",
  title: "Devansh Yadav | Bringing Ideas to Reality ✨",
  description: "Hi, I'm Devansh Yadav - Got ideas you are itching to bring to life? Let's collaborate and make it happen!",
  keywords: [
    "devansh yadav",
    "devansh",
    "devansh yadav",
    "portfolio",
    "devansh yadav portfolio",
    "devansh yadav 100x dev",
    "full stack developer",
    "designer",
    "web developer",
    "web designer",
    "react developer",
    "react designer",
    "next.js developer",
    "next.js designer",
    "devansh yadav portfolio",
    "devansh yadav website",
    "devansh yadav portfolio website",
    "devansh yadav portfolio website 2024",
    "devansh yadav portfolio 2024",
    "devansh yadav",
    "devansh yadav in",
    "devansh yadav.in", 
    "devansh yadav portfolio",
    "devansh yadav portfolio 2024",
    "devansh yadav portfolio website",
    "devansh yadav portfolio website 2024",
    "devansh yadav portfolio 2024 website",
    "devansh yadav portfolio 2024 website 2024",
    "devansh yadav portfolio 2024 website 2025",
    "devansh yadav portfolio 2025",
    "devansh yadav portfolio 2025 website",
    "devansh yadav portfolio 2025 website 2025",
  ],
  siteUrl: "https://devansh.is-a.dev",
  creator: {
    name: "Devansh Yadav",
    url: "https://devansh.is-a.dev",
  },
  ogImage: "https://devansh.is-a.dev/meta_thumb2.png",
  links: {
    x: "https://x.com/devanshyadav",
    github: "https://github.com/devanshyadav",
  }
}